 version : 2.1
 jobs:
    build:
      docker:
        - image: cimg/python:3.11
      steps:
        - checkout
        - run: pyhton main.py

    # test :
    #   docker:
    #     image: cimg/python:3.11
    #   steps:
    #     - checkout
    #     - run: python test.py 
    
    # deploy:
    #   docker: 
    #     - image: cimg/python:3.11
    #   steps:
    #     - run: echo " hello deployement done successfully "
  

  workflows:
      build:
         jobs:  
           - build 




